### ISSUE TITLE
Can't Service Binary Files

### ISSUE THREAD

**Issue by zoffixznet** [supernovus/perl6-psgi#6]
It seems [this line](https://github.com/supernovus/perl6-psgi/blob/cb8e26e57bb104a64d89b75ada6d02cdd0949aa4/lib/PSGI.pm6#L18) declares `$output` to be a `Str` by mistake. The comments above it indicate it can be other types as well.

This prevents apps like `Bailador` from service binary content, like image files. Removing `Str` from that line makes that type of things work correctly.

**Comment by supernovus** [comment]
I will take a look. The $output variable is always treated as a string, regardless of the $body content, which should use .encode() to convert from Buf. It's been quite a while since I personally worked on this library. It has received several updates from other contributors since that though.

**Comment by supernovus** [comment]
This should be fixed as per pull request #7

**Comment by zoffixznet** [comment]
Unfortunatelly the issue hasn't been fixed. @davepagurek 's tests and fix assume an encoding of text data into a binary stream, but that doesn't apply to, say, serving images.

The `$body.encode` in the added tests results in `utf8` type, not in a `Buf` type obtained from .slurp of binary files:

```perl6
$ perl6 -e '"foo".encode.WHAT.say'
(utf8)
```

**Comment by zoffixznet** [comment]
Actually, the issue seems to be elsewhere, as Stringy does take a Buf.

However, I'm still getting an error when trying to serve binary file with Baildator:

```
Type check failed in assignment to $output; expected Str but got Buf (Buf.new(72,84,84,80,4...)
  in any  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm line 1
  in any  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm line 1
  in sub encode-psgi-response at sources/4495C7B7918EE565D66335BB81FAC9AD441D4477 (PSGI) line 47
  in sub encode-psgi-response at sources/4495C7B7918EE565D66335BB81FAC9AD441D4477 (PSGI) line 103
  in sub encode-psgi-response at sources/4495C7B7918EE565D66335BB81FAC9AD441D4477 (PSGI) line 94
  in method handler at sources/7A1CB8E5EE1C15B75635DFF3AB1EF14A59C13BED (HTTP::Easy::PSGI) line 45
  in method run at sources/1E501B4ADD181EB20112AA83E1326E07497BC6F5 (HTTP::Easy) line 184
  in sub baile at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/D57520A5A045A33D405E36DAA759641E90C1FD99 (Bailador) line 91
  in block <unit> at app.p6 line 8
```

**Comment by zoffixznet** [comment]
Sorry. Never mind. It seems I was having issues with `panda` not installing the latest module version. A clean install resolved my issue.

**Comment by davepagurek** [comment]
It's worth noting that although this can serve images, it does it synchronously (even when you send an image as a supply, it loads it all into memory in order to send it out.) Ideally we'd want to stream it directly, but we might need an interface change for that.

**Comment by supernovus** [comment]
Most of the asynchronous stuff has yet to be implemented, either in the PSGI library, or in any of the underlying service libraries. The way the current encode-psgi-response method works converts the entire PSGI response into an HTTP response before returning it to the caller. I think in the future, a solution would be to offer a :stream flag that would encode the headers, and return the body as a Supply for the underlying server library to stream back to the client. I need to do a lot more reading of the current Perl 6 specifications, as the last time I actively worked on these libraries (beyond fixing a couple bugs here and there), Supply did not exist and there was no asynchronous stuff implemented in any of the Perl 6 runtimes.
